export const SET_ROUTE_PROFILE='SET_ROUTE_PROFILE';
export const RESET_ROUTE_PROFILE='RESET_ROUTE_PROFILE';

export const LOGIN_REQUEST_STARTS='LOGIN_REQUEST_STARTS'
export const LOGIN_REQUEST_ENDS='LOGIN_REQUEST_ENDS'
export const LOGIN_REQUEST_FAILED='LOGIN_REQUEST_FAILED'
export const LOGIN_REQUEST_SUCCESS='LOGIN_REQUEST_SUCCESS'
export const LOGIN_LOGOUT='LOGIN_LOGOUT'
export const LOGIN_PERFORM_LOGIN='LOGIN_PERFORM_LOGIN'
export const LOGIN_RESET_STATE='LOGIN_RESET_STATE'

//SPECIES

export const SPECIES_REQUEST_STARTS='SPECIES_REQUEST_STARTS';
export const SPECIES_REQUEST_ENDS='SPECIES_REQUEST_ENDS';
export const SPECIES_REQUEST_FAILED='SPECIES_REQUEST_FAILED';
export const SPECIES_REQUEST_SUCCESS='SPECIES_REQUEST_SUCCESS';
export const SPECIES_PERFORM_FETCH='SPECIES_PERFORM_FETCH';
export const SPECIES_RESET_STATE='SPECIES_RESET_STATE';